config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root to: 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resource :profile, only: [:show, :edit, :update]
  resources :users, only: [:show]
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id          :bigint           not null, primary key
#  accountname :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'updated!!'
    else
      flash.now[:error] = 'update failed...'
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :avatar
    )
  end
end

app/views/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message

= form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f| 
  %div
    = f.label :avatar, 'Avatar'
  %div
    = f.file_field :avatar
  %div
    = f.label :username, 'Username'
  %div
    = f.text_field :username, class: 'text'
  %div
    = f.label :introduction, 'Bio'
  %div
    = f.text_area :introduction

  = f.submit 'SUBMIT', class: 'btn-primary'

app/views/profiles/show.html.haml
.profilePage
  .container
    .profilePage_user_displayName 
      = current_user.display_name
    .profilePage_image
      -# = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
        = f.label :avatar do
          = image_tag current_user.avatar_image, class: 'avatar-image'
        %div
          = f.file_field :avatar, class: 'hidden uploader'
    .profilePage_dataContainer
      .profilePage_dataContainer_inner
        %p 44
        %p Posts
      .profilePage_dataContainer_inner
        %p 44
        %p Followers
      .profilePage_dataContainer_inner
        %p 44
        %p Following
    .profilePage_actionButton
      = link_to 'Edit', edit_profile_path
    .profilePage_imgBox 
      = image_tag 'img3.png'
      %div
        = image_tag 'img2.png'
        = image_tag 'img1.png'
        
= javascript_pack_tag 'profile'